version: 2
jobs:
    build:
        working_directory: ~
        docker:
            - image: circleci/node:10.15.1
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                key: dependency-cache-{{ checksum "frontend/package.json" }}
            - run:
                name: Install dependencies frontend
                command: cd frontend; npm install
            - save_cache:
                key: dependency-cache-{{ checksum "frontend/package.json" }}
                paths:
                    - .frontend/node_modules
            - run:
                name: Test frontend
                command: cd frontend; npm run test
            - restore_cache:
                key: dependency-cache-{{ checksum "backend/package.json" }}
            - run:
                name: Install dependencies backend
                command: cd backend; npm install
            - save_cache:
                key: dependency-cache-{{ checksum "backend/package.json" }}
                paths:
                    - .backend/node_modules
            - run:
                name: Test backend
                command: cd backend; npm run test